feat: Updates Stylelint to v14
Netcentric/fe-build pull request #55
Opened 2022-04-08 20:01 UTC by raohmaru

## Description

Updates dependency Stylelint to v14, which introduces breaking changes in the syntax parser. A project must update the [Stylelint configuration object]((https://stylelint.io/user-guide/configure/)) to use a shared syntax like @netcentric/stylelint-config (explained in the Migration guide).

Additionally, Stylelint v13 was not compatible with @netcentric/stylelint-config (which requires Stylelint v14).

## Related Issue

Fixes #49.
Fixes dependency tree error due to eslint-plugin-import version mismatch with ESLint v7.

## Types of changes

- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] I have read the **[CONTRIBUTING](docs/CONTRIBUTING.mnd)** document.
- [ ] All new and existing tests passed.

2022-04-10 18:05 UTC, easingthemes submitted a review, later dismissed

2022-04-11 06:36 UTC, quicoto approved these changes

2022-04-11 14:13 UTC, easingthemes commented
`Feat` commit message prefix is not going to bump new major version, just minor.
Use: 
```
BREAKING CHANGE: <breaking change summary>
<BLANK LINE>
<breaking change description + migration instructions>
```
https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit-message-footer

2022-04-11 14:14 UTC, easingthemes requested changes
Feat commit message prefix is not going to bump new major version, just minor.
Use:
```
BREAKING CHANGE: <breaking change summary>
<BLANK LINE>
<breaking change description + migration instructions>
```
https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit-message-footer

2022-04-13 07:48 UTC, easingthemes approved these changes

2022-05-05 16:03 UTC, merged